openapi: 3.1.0
info:
  title: SUAPS Agent API (No-Auth Dev Mode)
  version: "1.0.1"
servers:
  - url: https://suaps-brain.onrender.com

paths:
/upload:
  post:
    operationId: upload
    requestBody:
      required: true
      content:
        multipart/form-data:
          schema:
            type: object
            properties:
              file:
                type: string
                format: binary
              tags:
                type: string
    responses:
      "200":
        description: Upload + ingest started
        content:
          application/json:
            schema:
              type: object
              properties:
                file_id: { type: string }
                bytes: { type: integer }
                mime_type: { type: string }
                ingest_ids: { type: array, items: { type: string } }
                latency_ms: { type: integer }
/debug/memories:
  get:
    operationId: debugMemories
    parameters:
      - in: query
        name: limit
        schema: { type: integer, default: 20 }
      - in: query
        name: type
        schema: { type: string, nullable: true }
    responses:
      "200":
        description: Latest memories
        content:
          application/json:
            schema:
              type: object
              properties:
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      id: { type: string }
                      type: { type: string }
                      title: { type: string }
                      tags: { type: array, items: { type: string } }
                      created_at: { type: string }
  /healthz:
    get:
      operationId: healthz
      x-openai-isConsequential: false
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok: { type: boolean }
                  auth_disabled: { type: boolean }

  /whoami:
    get:
      operationId: whoami
      x-openai-isConsequential: false
      parameters:
        - in: query
          name: user_email
          schema: { type: string, nullable: true }
        - in: query
          name: user_id
          schema: { type: string, nullable: true, description: "Optional; non-UUID treated as alias" }
      responses:
        "200":
          description: Current resolved user (dev helper)
          content:
            application/json:
              schema:
                type: object
                properties:
                  authorized: { type: boolean }
                  user:
                    type: object
                    properties:
                      id: { type: string }
                      email: { type: string, nullable: true }

  /chat:
    post:
      operationId: chat
      x-openai-isConsequential: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [message]
              properties:
                user_email:  { type: string, nullable: true }
                # user_id allowed for compatibility but not required and ignored for writes
                user_id:     { type: string, nullable: true, description: "Optional; ignored for writes if non-UUID" }
                session_id:  { type: string, nullable: true }
                message:     { type: string }
                temperature: { type: number, nullable: true, description: "0.0–1.2; optional" }
                history:
                  type: array
                  items:
                    type: object
                    required: [role, content]
                    properties:
                      role:
                        type: string
                        enum: [user, assistant, system]
                      content:
                        type: string
      responses:
        "200":
          description: Chat response
          content:
            application/json:
              schema:
                type: object
                properties:
                  session_id: { type: string }
                  answer: { type: string }

  /memories/upsert:
    post:
      operationId: upsertMemory
      x-openai-isConsequential: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [type, content]
              properties:
                # REMOVE user_id from writes to prevent clients sending email into UUID field
                user_email: { type: string, nullable: true }
                type:
                  type: string
                  enum: [episodic, semantic, procedural]
                title:      { type: string, nullable: true }
                content:    { type: string }
                importance: { type: integer, default: 3 }
                tags:
                  type: array
                  items: { type: string }
      responses:
        "200":
          description: Upserted memory id
          content:
            application/json:
              schema:
                type: object
                properties:
                  id: { type: string }

  /ingest/batch:
    post:
      operationId: ingestBatch
      x-openai-isConsequential: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [items]
              properties:
                items:
                  type: array
                  items:
                    type: object
                    required: [text, type]
                    properties:
                      # REMOVE user_id from writes
                      user_email: { type: string, nullable: true }
                      text:       { type: string }
                      type:
                        type: string
                        enum: [semantic, episodic]
                      tags:
                        type: array
                        items: { type: string }

components:
  schemas: {}
