name: Ingest ClickUp Wiki to Pinecone

on:
  workflow_dispatch: {}      # run manually from Actions tab
  push:
    paths:
      - 'wiki/**.md'

jobs:
  ingest:
    runs-on: ubuntu-latest

    # Make all `run:` steps use bash, consistently
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build ingest payload (Markdown -> JSON)
        run: |
          set -euo pipefail
          python scripts/make_ingest_payload.py "${{ secrets.SUAPS_USER_EMAIL }}" > payload.json
          echo "Built payload.json"
          jq -r '.items | length' payload.json > item_count.txt

      - name: Show item count
        run: |
          set -euo pipefail
          COUNT="$(cat item_count.txt)"
          echo "Items to ingest -> ${COUNT}"

      - name: POST to /ingest/batch
        env:
          API_URL: https://suaps-brain.onrender.com/ingest/batch
          API_KEY: ${{ secrets.SUAPS_ACTIONS_API_KEY }}
        run: |
          set -euo pipefail
          COUNT="$(cat item_count.txt)"
          if [ "${COUNT}" = "0" ]; then
            echo "No items to ingest; skipping."
            exit 0
          fi
          echo "Posting ${COUNT} items to ${API_URL} ..."
          HTTP_CODE=$(curl -sS -o resp.json -w "%{http_code}" \
            -X POST "${API_URL}" \
            -H "Content-Type: application/json" \
            -H "X-API-Key: ${API_KEY}" \
            --data-binary @payload.json)
          echo "HTTP ${HTTP_CODE}"
          echo "Response body:" && cat resp.json && echo
          test "${HTTP_CODE}" = "200"
