name: Ingest ClickUp Wiki to Pinecone

on:
  workflow_dispatch: {}      # run manually from Actions tab
  push:
    paths:
      - 'wiki/**.md'

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build ingest payload (Markdown -> JSON)
        shell: bash
        run: |
          python scripts/make_ingest_payload.py "${{ secrets.SUAPS_USER_EMAIL }}" > payload.json
          echo "Built payload.json"
          jq -r '.items | length' payload.json > item_count.txt

      - name: Show item count
        shell: bash
        run: |
          echo "Items to ingest: $(cat item_count.txt)"

      - name: POST to /ingest/batch
        shell: bash
        env:
          API_URL: https://suaps-brain.onrender.com/ingest/batch
          API_KEY: ${{ secrets.SUAPS_ACTIONS_API_KEY }}
        run: |
          ITEMS=$(cat item_count.txt)
          if [ "$ITEMS" -eq 0 ]; then
            echo "No items to ingest; skipping."
            exit 0
          fi
          curl -sS -X POST "$API_URL" \
            -H "Content-Type: application/json" \
            -H "X-API-Key: $API_KEY" \
            --data-binary @payload.json
