name: Ingest ClickUp Wiki to Pinecone

on:
  workflow_dispatch: {}    # run manually from Actions tab
  push:
    paths:
      - 'wiki/**.md'

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build ingest payload (Markdown -> JSON)
        id: payload
        run: |
          python scripts/make_ingest_payload.py "${{ secrets.SUAPS_USER_EMAIL }}" > payload.json
          echo "len=$(jq '.items | length' payload.json)" >> $GITHUB_OUTPUT
          echo "payload=$(cat payload.json | jq -c '.')" >> $GITHUB_OUTPUT

      - name: Show item count
        run: echo "Items to ingest: ${{ steps.payload.outputs.len }}"

      - name: POST to /ingest/batch
        if: ${{ steps.payload.outputs.len != '0' }}
        env:
          API_URL: https://suaps-brain.onrender.com/ingest/batch
          API_KEY: ${{ secrets.SUAPS_ACTIONS_API_KEY }}
        run: |
          curl -sS -X POST "$API_URL" \
            -H "Content-Type: application/json" \
            -H "X-API-Key: $API_KEY" \
            -d '${{ steps.payload.outputs.payload }}'
